Repository websterzh/vatprc-wiki, pull requests merged in 2022-04, with the labels that each got.

#18 Navigation
  PBN进离场.md
  传统进离场.md
Labels: Done

#16 Code of conduct
  COC_translate_full.md
Labels: FIXME, DO NOT MERGE

#36 Outline
  Outline.md
Labels: Done

#31 Flightrule IFR
  FlightRules/AircraftsTable.md
  FlightRules/IFR.md
Labels: FIXME, Review Required

#17 大流量活動
  bigflow_event.md
Labels: Done

#22 xPilot
  images/COM1.png
  images/ClientCSLError.png
  images/ConfirmDownloadToken.png
  images/DownloadModels.png
  images/Flightplan.png
  images/InstallDirectory.png
  images/ModelDownloadGetToken.png
  images/ModelsDownloading.png
  images/ModelsInstalling.png
  images/ModelsXplaneFolder.png
  images/NewVersionAvailable.png
  images/NewVersionDownloading.png
  images/PluginMenu.png
  images/X-Plane_Settings_Joystick.png
  images/X-Plane_Settings_JoystickPTT.png
  images/X-Plane_Settings_KeyboardPTT.png
  images/XplaneCSLConfiguration.png
  images/XplanePath.png
  images/nearby_atc.png
  images/xPilot_Adm.png
  images/xPilot_ModeC.png
  images/xPilot_ModeC_IDENT.png
  images/xPilot_Settings.png
  images/xPilot_before_connect.png
  images/xPilot_main.png
  images/xPilot_main_connected.png
  images/xpilot_in_xp.png
  xPilot 使用文档.md
Labels: DO NOT MERGE, Review Required
